    let quilometro = 0;
    let metro = 0;
    let centimetro = 0;
    let milimetro = 0;
    let micrometro = 0;
    let nanometro = 0;
    let milha = 0;
    let jarda = 0;
    let pe = 0;
    let polegada = 0;
    let milha_n = 0;

    function calculate() {
        resultado.innerHTML = "";
        let valor = Number(place.value);
        if (medidas.value == 'km') {
            metro = (valor * 1000);
            centimetro = (valor * 100000);
            milimetro = (valor * 1000000);
            micrometro = (valor * 1000000000);
            nanometro = (valor * 1000000000000);
            milha = (valor / 1.609);
            jarda = (valor * 1094);
            pe = (valor * 3281);
            polegada = (valor * 39370);
            milha_n = (valor / 1.852);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'm') {
            quilometro = (valor / 1000);
            centimetro = (valor * 100);
            milimetro = (valor * 1000);
            micrometro = (valor * 1000000);
            nanometro = (valor * 1000000000);
            milha = (valor / 1609);
            jarda = (valor * 1.094);
            pe = (valor * 3.281);
            polegada = (valor * 39.37);
            milha_n = (valor / 1852);
            resultado.style.display = 'block';
            resultado.innerHTML = `O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'cm') {
            quilometro = (valor / 100000);
            metro = (valor * 100);
            milimetro = (valor * 10);
            micrometro = (valor * 10000);
            nanometro = (valor * 10000000);
            milha = (valor / 160934);
            jarda = (valor / 91.44);
            pe = (valor / 30.48);
            polegada = (valor / 2.54);
            milha_n = (valor / 185200);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetro = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'mm') {
            quilometro = (valor / 100000);
            metro = (valor / 1000);
            centimetro = (valor / 10);
            micrometro = (valor * 1000);
            nanometro = (valor * 100000);
            milha = (valor / 1.609000000);
            jarda = (valor / 914);
            pe = (valor / 305);
            polegada = (valor / 25.4);
            milha_n = (valor / 1.852000000);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'mc') {
            quilometro = (valor / 1000000000);
            metro = (valor * 1000000);
            centimetro = (valor * 10000);
            milimetro = (valor * 1000);
            nanometro = (valor / 1000);
            milha = (valor / 1.609000000000);
            jarda = (valor / 914400);
            pe = (valor / 304800);
            polegada = (valor / 25400);
            milha_n = (valor / 1.852000000000);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetro = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'nm') {
            quilometro = (valor / 1000000000000);
            metro = (valor / 1000000000);
            centimetro = (valor / 10000000);
            milimetro = (valor / 1000000);
            micrometro = (valor / 1000);
            milha = (valor / 1.609000000000000);
            jarda = (valor / 9.14400000000);
            pe = (valor / 3.04800000000);
            polegada = (valor / 2.540000000);
            milha_n = (valor / 1.852000000000000);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'mi') {
            quilometro = (valor * 1.609);
            metro = (valor * 1609);
            centimetro = (valor * 160934);
            milimetro = (valor * 1.609000000);
            micrometro = (valor * 1.609000000000);
            nanometro = (valor * 1.609000000000000);
            jarda = (valor * 1760);
            pe = (valor * 5280);
            polegada = (valor * 63360);
            milha_n = (valor / 1.151);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'yd') {
            quilometro = (valor * 1094);
            metro = (valor * 1.904);
            centimetro = (valor * 91.44);
            milimetro = (valor * 914);
            micrometro = (valor * 914400);
            nanometro = (valor * 9.14400000000);
            milha = (valor / 1760);
            pe = (valor * 3);
            polegada = (valor * 36);
            milha_n = (valor / 2025);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'ft') {
            quilometro = (valor / 3281);
            metro = (valor / 3.281);
            centimetro = (valor * 30.48);
            milimetro = (valor * 305);
            micrometro = (valor * 304800);
            nanometro = (valor * 3.04800000000);
            milha = (valor / 5280);
            jarda = (valor / 3);
            polegada = (valor * 12);
            milha_n = (valor / 6076);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Polegadas = ${polegada}"<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'inch') {
            quilometro = (valor / 39370);
            metro = (valor / 39.37);
            centimetro = (valor * 2.54);
            milimetro = (valor * 25.4);
            micrometro = (valor * 25400);
            nanometro = (valor * 2.540000000);
            milha = (valor / 63360);
            jarda = (valor / 36);
            pe = (valor / 12);
            milha_n = (valor / 72913);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Milhas Náuticas = ${milha_n}m/h`;
        } else if (medidas.value == 'mn') {
            quilometro = (valor / 1.852);
            metro = (valor * 1852);
            centimetro = (valor * 185200);
            milimetro = (valor * 1.852000000);
            micrometro = (valor * 1.852000000000);
            nanometro = (valor * 1.852000000000000);
            milha = (valor * 1.151);
            jarda = (valor * 2025);
            pe = (valor * 6076);
            polegada = (valor * 72913);
            resultado.style.display = 'block';
            resultado.innerHTML = ` O resultado da conversão em:<br>
                Quilômetros = ${quilometro}km<br>
                Metros = ${metro}m<br>
                Centímetros = ${centimetro}cm<br>
                Milímetros = ${milimetro}mm<br>
                Micrômetros = ${micrometro}μm<br>
                Nanômetros = ${nanometro}nm<br>
                Milhas = ${milha}mi<br>
                Jardas = ${jarda}yd<br>
                Pés = ${pe}ft<br>
                Polegadas = ${polegada}"`;
        } else {
            alert ('Escolha uma unidade de medida correta!');
        }

    }